pipeline{
    agent any
    stages{
        stage("Fetch Code"){
            steps{
                git branch: 'paac', url: 'https://github.com/devopshydclub/vprofile-project.git'
            }
        }
        stage("Build Code"){
            steps{
                sh 'mvn install'
            }
        }
        stage("Run Test Cases"){
            steps{
                sh 'mvn test'
            }
        }
    }
}